export const DEFAULT_ASSET_TYPE = "clinical-trial";

interface AssetOption {
  value: string;
  label: string;
  indexName: string;
  primaryField: string;
}

export const ASSET_OPTIONS: AssetOption[] = [
  {
    value: "clinical-trial",
    label: "Clinical Trial",
    indexName: "clinical_trial_db_schema",
    primaryField: "trial_number_id",
  },
  {
    value: "drug",
    label: "Drug",
    indexName: "drug_db_schema",
    primaryField: "drug_id",
  },
  {
    value: "device",
    label: "Device",
    indexName: "device_db_schema",
    primaryField: "device_id",
  },
];

const LOCATION_OPTIONS = [
  "Argentina",
  "Australia",
  "Austria",
  "Belgium",
  "Botswana",
  "Brazil",
  "Bulgaria",
  "Burkina Faso",
  "Cambodia",
  "Cameroon",
  "Canada",
  "China",
  "Colombia",
  "Croatia",
  "Cyprus",
  "Czech Republic",
  "Czechia",
  "Denmark",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "Estonia",
  "Ethiopia",
  "Finland",
  "France",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Hong Kong",
  "Hungary",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Korea",
  "Kuwait",
  "Lebanon",
  "Lithuania",
  "Malawi",
  "Malaysia",
  "Mali",
  "Mexico",
  "Netherlands",
  "New Zealand",
  "Nigeria",
  "Norway",
  "Pakistan",
  "Panama",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russian Federation",
  "Rwanda",
  "Saudi Arabia",
  "Serbia",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "South Africa",
  "Spain",
  "Sweden",
  "Switzerland",
  "Syria",
  "Syrian Arab Republic",
  "Taiwan",
  "Tanzania",
  "Thailand",
  "Tunisia",
  "Türkiye",
  "Turkey",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "United States of America",
  "Venezuela",
  "Viet Nam",
  "Vietnam",
  "Zambia",
  "Zimbabwe",
];

const TRIAL_PHASE_OPTIONS = [
  "Preclinical",
  "Early Phase I",
  "Phase I",
  "Phase II",
  "Phase III",
  "Approved",
  "Phase IV",
];

const TRIAL_REGISTRY_OPTIONS = [
  "U.S. Clinical Trials Registry",
  "EU Clinical Trials Register",
  "Global Clinical Trials Registry",
  "Korean Clinical Trials Registry",
  "China Clinical Trial Registry",
  "Taiwan Clinical Trials Registry",
];

const SUBJECT_TYPE_OPTIONS = ["Human", "Animals"];

const TRIAL_STATUS_OPTIONS = [
  "Completed",
  "Recruiting",
  "Not Yet Recruiting",
  "Active, Not Recruiting",
  "Terminated",
  "Withdrawn",
  "Suspended",
  "Enrolling by Invitation",
  "Withheld",
  "No Longer Available",
  "Available",
  "Approved for Marketing",
  "Temporarily Not Available",
  "Deferred",
];

const DRUG_REGISTRY_OPTIONS = [
  "Taiwan_FDA",
  "U.S. Approved Drugs",
  "China Clinical Trial Tacit Approval",
  "China Domestic Drug",
  "Europe HMA Drugs",
  "China Imported Drug",
  "Europe EMA Drugs",
];

const DRUG_MARKETING_STATUS_OPTIONS = [
  "Marketed",
  "Authorised",
  "Discontinued",
  "Prescription",
  "Withdrawn",
  "None (Tentative Approval)",
  "Over-the-counter",
  "Application withdrawn",
  "Refused",
  "Opinion",
  "Lapsed",
  "Expired",
  "Revoked",
  "Opinion under re-examination",
  "Suspended",
  "Withdrawn from rolling review",
];

const DRUG_DOSAGE_FORM_OPTIONS = [
  "Tablet",
  "Slice",
  "Injection",
  "Injectable",
  "Capsule",
  "Film-coated tablet",
  "Solution",
  "Capsules",
  "Dry powder injection",
  "External liquid",
  "tablet",
  "Eye juice",
  "Tablet Extended Release",
  "Crystal injection",
  "Granule agent",
  "In-house pills",
  "Spray",
  "Syrup",
  "Soft capsule",
  "Cream",
  "Powder",
  "Pills (Dami Pills)",
  "Solution Drops",
  "Topical gel",
  "Ointment",
  "Capsule, hard",
  "Mixture",
  "Capsule Extended Release",
  "Suspension",
  "Injection fluid",
  "For Suspension",
  "Gel",
  "Liquid",
  "Dialysis fluid",
  "Pill",
  "Tablet Delayed Release",
  "Solution for injection",
  "Oral solution",
  "For Solution",
  "Nasal spray",
  "Chewing",
  "Eye ointment",
  "Lotion",
  "Powder for oral suspension",
  "Pills (water pills)",
  "Wine agent",
  "Tablet Orally Disintegrating",
  "Tablet Chewable",
  "Tablets (icing-coated tablets)",
  "Granules",
  "Oral inhaler",
  "Capsule Delayed Rel Pellets",
  "Drops",
  "Powder for liquid",
  "Elixir",
  "Orodispersible tablet",
  "Suspension Drops",
  "Solution for infusion",
  "Concentrate",
  "Capsule Delayed Release",
  "Patch Slice",
  "Dry Injection of Crystal",
  "Gastro-resistant tablet",
  "Topical spray",
  "Film Extended Release",
  "Pills",
  "Intraoral paste",
  "Aerosol Metered",
  "Ophthalmic preparations",
  "Tincture",
  "Oral suspension",
  "Decoction cream (ointment)",
  "Capsule, soft",
  "Prolonged-release tablet",
  "Effervescent tablet",
  "Oral spray",
  "Capsules (hard capsules)",
  "Eye drops",
  "Oral dissolving",
  "Tablet For Suspension",
  "Nasal fluid",
  "Eye wash",
  "Foaming",
  "Hard air capsule",
  "Implant",
  "Patch",
  "Chewable tablet",
  "Dispersible tablet",
  "Inhalation liquid",
  "Powder for solution for injection",
  "Gel agent",
  "Powder for oral solution",
  "Powder for solution for infusion",
];

export const DRUG_DATE_FIELD_OPTIONS = [
  {
    label: "Submission Status Date",
    value: "submission_status_date",
  },
  {
    label: "Opinion Date",
    value: "opinion_date",
  },
  {
    label: "Authorization Date",
    value: "application_date",
  },
  {
    label: "Last Update Date",
    value: "last_update_date",
  },
];

export const CLINICAL_TRIAL_DATE_FIELD_OPTIONS = [
  {
    label: "Study Start",
    value: "start_date",
  },
  {
    label: "Study Completion",
    value: "primary_completion_date",
  },
  {
    label: "Primary Completion",
    value: "completion_date",
  },
  {
    label: "First Post",
    value: "first_posted",
  },
  {
    label: "Last Update Post",
    value: "last_update_posted",
  },
  {
    label: "Register Date",
    value: "register_date",
  },
];

export const DEVICE_DATE_FIELD_OPTIONS = [
  {
    label: "Approval Date",
    value: "approval_date",
  },
  {
    label: "Update Date",
    value: "modification_date",
  },
  {
    label: "Expiry Date",
    value: "expiry_date",
  },
  {
    label: "Cancellation Date",
    value: "cancellation_date",
  },
];

const DEVICE_REGISTRY_OPTIONS = ["U.S. FDA-Device", "Taiwan FDA-Device"];

const DEVICE_CLASS_OPTIONS = [
  "Class I",
  "Class II",
  "Class III",
  "Unclassified",
];

export const ASSET_FILTERS: Record<string, any[]> = {
  "clinical-trial": [
    {
      id: "locations",
      label: "Region / Country",
      queryParam: "location",
      field: "locations",
      facetField: "locations.keyword",
      type: "multi",
      options: LOCATION_OPTIONS,
      searchable: true,
    },
    {
      id: "trial_registry_T",
      label: "Trial Registry",
      queryParam: "registry",
      field: "trial_registry_T",
      facetField: "trial_registry_T.keyword",
      type: "multi",
      options: TRIAL_REGISTRY_OPTIONS,
    },
    {
      id: "trial_status",
      label: "Trial Status",
      queryParam: "status",
      field: "trial_status",
      facetField: "trial_status.keyword",
      type: "multi",
      options: TRIAL_STATUS_OPTIONS,
    },
    {
      id: "trial_phase",
      label: "Trial Phase",
      queryParam: "phase",
      field: "trial_phase",
      facetField: "trial_phase.keyword",
      type: "multi",
      options: TRIAL_PHASE_OPTIONS,
    },
    {
      id: "subject_type",
      label: "Subject Type",
      queryParam: "subject_type",
      field: "subject_type",
      facetField: "subject_type.keyword",
      type: "multi",
      options: SUBJECT_TYPE_OPTIONS,
    },
    {
      id: "clinical_trial_date",
      label: "Clinical Trial Date",
      queryParam: "clinical_trial_date",
      type: "milestone-date",
      options: CLINICAL_TRIAL_DATE_FIELD_OPTIONS,
    },
  ],
  drug: [
    {
      id: "region_country",
      label: "Region / Country",
      queryParam: "location",
      field: "region_country",
      facetField: "region_country.keyword",
      type: "multi",
      options: LOCATION_OPTIONS,
      searchable: true,
    },
    {
      id: "drug_registry_T",
      label: "Drug Registry",
      queryParam: "registry",
      field: "drug_registry_T",
      facetField: "drug_registry_T.keyword",
      type: "multi",
      options: DRUG_REGISTRY_OPTIONS,
    },
    {
      id: "marketing_status",
      label: "Marketing Status",
      queryParam: "marketing_status",
      field: "marketing_status",
      facetField: "marketing_status.keyword",
      type: "multi",
      options: DRUG_MARKETING_STATUS_OPTIONS,
    },
    {
      id: "dosage_form",
      label: "Dosage Form",
      queryParam: "dosage_form",
      field: "dosage_form",
      facetField: "dosage_form.keyword",
      type: "multi",
      options: DRUG_DOSAGE_FORM_OPTIONS,
    },
    {
      id: "drug_date",
      label: "Drug Date",
      queryParam: "drug_date",
      type: "milestone-date",
      options: DRUG_DATE_FIELD_OPTIONS,
    },
  ],
  device: [
    {
      id: "region_country",
      label: "Region / Country",
      queryParam: "location",
      field: "region_country",
      facetField: "region_country.keyword",
      type: "multi",
      options: LOCATION_OPTIONS,
      searchable: true,
    },
    {
      id: "device_registry_T",
      label: "Device Registry",
      queryParam: "registry",
      field: "device_registry_T",
      facetField: "device_registry_T.keyword",
      type: "multi",
      options: DEVICE_REGISTRY_OPTIONS,
    },
    {
      id: "device_class",
      label: "Device Class",
      queryParam: "device_class",
      field: "device_class",
      facetField: "device_class.keyword",
      type: "multi",
      options: DEVICE_CLASS_OPTIONS,
    },
    {
      id: "device_date",
      label: "Device Date",
      queryParam: "device_date",
      type: "milestone-date",
      options: DEVICE_DATE_FIELD_OPTIONS,
    },
  ],
};

export const ASSET_TABLE_COLUMNS: Record<string, any[]> = {
  "clinical-trial": [
    {
      id: "trial_number_id",
      label: "Trial Number",
      field: "trial_number_id",
      className: "min-w-52",
    },
    {
      id: "study_title",
      label: "Study Title",
      field: "study_title",
      className: "min-w-[312px]",
    },
    {
      id: "trial_phase",
      label: "Trial Phase",
      field: "trial_phase",
      className: "min-w-[132px]",
    },
    {
      id: "conditions",
      label: "Disease Condition",
      field: "conditions",
      className: "min-w-[210px]",
    },
    {
      id: "trial_status",
      label: "Trial Status",
      field: "trial_status",
      className: "min-w-[210px]",
    },
    {
      id: "organization",
      label: "Organization",
      field: "organization",
      className: "min-w-[272px]",
    },
    {
      id: "locations",
      label: "Region/Country",
      field: "locations",
      className: "min-w-[176px]",
    },
    {
      id: "trial_registry_T",
      label: "Trial Registry",
      field: "trial_registry_T",
      className: "min-w-[200px]",
    },
  ],
  drug: [
    {
      id: "drug_id",
      label: "Drug Number",
      field: "drug_id",
      className: "min-w-52",
    },
    {
      id: "drug_name",
      label: "Drug Name",
      field: "drug_name",
      className: "min-w-[240px]",
    },
    {
      id: "marketing_status",
      label: "Marketing Status",
      field: "marketing_status",
      className: "min-w-[200px]",
    },
    {
      id: "conditions",
      label: "Disease Condition",
      field: "conditions",
      className: "min-w-[210px]",
    },
    {
      id: "dosage_form",
      label: "Dosage Form",
      field: "dosage_form",
      className: "min-w-[200px]",
    },
    {
      id: "route",
      label: "Route / Spec",
      field: "route",
      className: "min-w-[180px]",
    },
    {
      id: "organization",
      label: "Organization",
      field: "organization",
      className: "min-w-[272px]",
    },
    {
      id: "region_country",
      label: "Region/Country",
      field: "region_country",
      className: "min-w-[176px]",
    },
    {
      id: "drug_registry_T",
      label: "Drug Registry",
      field: "drug_registry_T",
      className: "min-w-[200px]",
    },
  ],
  device: [
    {
      id: "device_id",
      label: "Device Number",
      field: "device_id",
      className: "min-w-52",
    },
    {
      id: "device_name",
      label: "Device Name",
      field: "device_name",
      className: "min-w-[240px]",
    },
    {
      id: "device_class",
      label: "Device Class",
      field: "device_class",
      className: "min-w-[160px]",
    },
    {
      id: "medical_specialty",
      label: "Medical Specialty",
      field: "medical_specialty",
      className: "min-w-[220px]",
    },
    {
      id: "organization",
      label: "Organization",
      field: "organization",
      className: "min-w-[272px]",
    },
    {
      id: "region_country",
      label: "Region / Country",
      field: "region_country",
      className: "min-w-[176px]",
    },
    {
      id: "device_registry_T",
      label: "Device Registry",
      field: "device_registry_T",
      className: "min-w-[200px]",
    },
  ],
};

export const getAssetOption = (value: string) =>
  ASSET_OPTIONS.find((asset) => asset.value === value);

export const getAssetFilters = (value: string) => ASSET_FILTERS[value] ?? [];

export const getAssetColumns = (value: string) =>
  ASSET_TABLE_COLUMNS[value] ?? [];
